name: dd_app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  dio: ^1.0.1
  cached_network_image: ^0.4.1
  flutter_staggered_grid_view: ^0.2.1
  # flutter_local_notifications: 
  # flutter_spinkit: ^1.0.0
  cupertino_icons: ^0.1.2
  url_launcher: ^3.0.3
  flutter_swiper: ^1.0.4
  shimmer: ^0.0.4
  share: ^0.5.2
  # open_file: ^1.0.2
  # flutter_circular_chart: ^0.0.3
  package_info: ^0.3.2
  connectivity: ^0.3.1
  timeago: ^2.0.3
  sqflite: any
  video_player: "^0.10.0"
#  flutter_statusbar_manager : any
  # dropdown_menu: ^1.1.0
  event_bus: ^1.0.1
#  video_player:
#    path: ../plugins/flutter_video_player
  flutter_dlan:
    path: ../plugins/flutter_dlan
  toasty:
    path: ../plugins/flutter_toasty
  clipboard:
    path: ../plugins/flutter_clipboard
  loading:
    path: ../plugins/flutter_loading
  webview:
    path: ../plugins/flutter_webview
  android_intent:
    path: ../plugins/android_intent
  tx_xg:
    path: ../plugins/flutter_tx_xg
  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/classify_icons/5b1362ab30763a214430d036.webp # 全部电影
   - images/classify_icons/5b0fd14e7cad175a34a2ea8a.webp # 动作片
   - images/classify_icons/5b0fd14e7cad175a34a2ea8b.webp # 喜剧片
   - images/classify_icons/5b0fd14e7cad175a34a2ea8c.webp # 爱情片
   - images/classify_icons/5b0fd14e7cad175a34a2ea8d.webp # 科幻片
   - images/classify_icons/5b0fd14e7cad175a34a2ea90.webp # 战争片
   - images/classify_icons/5b0fd14e7cad175a34a2ea8e.webp # 恐怖片
   - images/classify_icons/5b0fd14e7cad175a34a2ea8f.webp # 剧情片
   - images/classify_icons/5b6bd4eb50456c5fb99610f4.webp # 记录片
   - images/classify_icons/5b6bd55a50456c5fb99610f5.webp # 伦理片
   - images/classify_icons/5b6c1f84adcfce70593225a9.webp # 福利片
   - images/classify_icons/5b1fce6330025ae5371a6a8a.webp # 全部连续剧
   - images/classify_icons/5b1fcf0b30025ae5371a6ad8.webp # 国产剧
   - images/classify_icons/5b1fcf6330025ae5371a6b00.webp # 港台剧
   - images/classify_icons/5b1fcfb230025ae5371a6b22.webp # 日韩剧
   - images/classify_icons/5b1fcffb30025ae5371a6b41.webp # 欧美剧
   - images/classify_icons/5b1fd85730025ae5371abaed.webp # 全部综艺
   - images/classify_icons/5b1fdbee30025ae5371ac363.webp # 全部动漫
   - images/classify_icons/tv.webp # 直播
   - images/type_icons/zuidazy.webp # 最大资源
   - images/type_icons/kuyunzy.webp # 酷云资源
   - images/users/user-bg.webp # 用户背景
   - images/logo.webp # logo
   - images/img_load_failed.webp # 图片加载失败
   - images/img_loading.webp # 图片加载中
   - images/format/fla.webp # flash 图标
   - images/format/mp4.webp # mp4 图标
   - images/format/hls.webp # m3u8 图标
  #  - images/background.png # 背景
   - images/null-page-draw.webp # 页面没有数据
   - images/login_bg.webp # 登录页背景
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
